import { Difficulty, Quiz, QuizStatus } from "./generated/prisma";

export const sampleQuizzes: Quiz[] = [
	{
		id: "1",
		title: "Crypto Basics",
		description: "Learn the fundamentals of cryptocurrency in this beginner-friendly quiz.",
		totalQns: 10,
		totalPlayers: 1243,
		prize: 250,
		category: "Crypto",
		imageUrl:
			"https://images.unsplash.com/photo-1639322537504-6427a16b0a28?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "EASY" as Difficulty,
		createdAt: new Date("2025-09-20"),
		gamePin: "123456",
		hostId: "user_1",
		hostName: "Crypto Expert",
		currentQn: 0,
		timePerQn: 30,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "2",
		title: "Blockchain Masters",
		description: "Test your knowledge of advanced blockchain concepts and technologies.",
		totalQns: 15,
		totalPlayers: 987,
		prize: 500,
		category: "Blockchain",
		imageUrl:
			"https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "HARD" as Difficulty,
		createdAt: new Date("2025-09-25"),
		gamePin: "234567",
		hostId: "user_2",
		hostName: "Blockchain Developer",
		currentQn: 0,
		timePerQn: 45,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "3",
		title: "NFT Knowledge",
		description: "Everything you need to know about Non-Fungible Tokens in one quiz.",
		totalQns: 8,
		totalPlayers: 654,
		prize: 150,
		category: "NFTs",
		imageUrl:
			"https://images.unsplash.com/photo-1646458590637-ec1b2cdcb95d?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "MEDIUM" as Difficulty,
		createdAt: new Date("2025-09-28"),
		gamePin: "345678",
		hostId: "user_1",
		hostName: "NFT Artist",
		currentQn: 0,
		timePerQn: 30,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "4",
		title: "DeFi Exploration",
		description: "Explore the world of Decentralized Finance in this comprehensive quiz.",
		totalQns: 12,
		totalPlayers: 432,
		prize: 300,
		category: "DeFi",
		imageUrl:
			"https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "MEDIUM" as Difficulty,
		createdAt: new Date("2025-09-30"),
		gamePin: "456789",
		hostId: "user_2",
		hostName: "DeFi Specialist",
		currentQn: 0,
		timePerQn: 40,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "5",
		title: "Gaming in Crypto",
		description: "Where gaming and cryptocurrency meet. Test your knowledge!",
		totalQns: 10,
		totalPlayers: 876,
		prize: 200,
		category: "Gaming",
		imageUrl:
			"https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "EASY" as Difficulty,
		createdAt: new Date("2025-10-01"),
		gamePin: "567890",
		hostId: "user_1",
		hostName: "Gaming Expert",
		currentQn: 0,
		timePerQn: 25,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "6",
		title: "Tech Innovations",
		description: "Quiz about the latest technology innovations changing our world.",
		totalQns: 14,
		totalPlayers: 765,
		prize: 350,
		category: "Technology",
		imageUrl:
			"https://images.unsplash.com/photo-1581090700227-1e37b190418e?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "MEDIUM" as Difficulty,
		createdAt: new Date("2025-10-02"),
		gamePin: "678901",
		hostId: "user_2",
		hostName: "Tech Innovator",
		currentQn: 0,
		timePerQn: 35,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "7",
		title: "Science Quiz",
		description: "Test your knowledge of scientific discoveries and principles.",
		totalQns: 15,
		totalPlayers: 543,
		prize: 275,
		category: "Science",
		imageUrl:
			"https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "HARD" as Difficulty,
		createdAt: new Date("2025-10-03"),
		gamePin: "789012",
		hostId: "user_1",
		hostName: "Science Professor",
		currentQn: 0,
		timePerQn: 40,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
	{
		id: "8",
		title: "History Mysteries",
		description: "Journey through time with this history-themed quiz challenge.",
		totalQns: 12,
		totalPlayers: 432,
		prize: 225,
		category: "History",
		imageUrl:
			"https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=500&h=300&auto=format&fit=crop",
		difficulty: "MEDIUM" as Difficulty,
		createdAt: new Date("2025-10-04"),
		gamePin: "890123",
		hostId: "user_2",
		hostName: "History Buff",
		currentQn: 0,
		timePerQn: 35,
		status: "DRAFT" as QuizStatus,
		startedAt: null,
		endedAt: null,
	},
];
